# Generated by Django 3.1.3 on 2020-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPN', 'Open'), ('COM', 'Complete'), ('SUS', 'Suspension'), ('CNX', 'Canceled')], default=0, max_length=3),
        ),
    ]
