# Generated by Django 3.1.3 on 2020-11-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201119_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPN', 'Open'), ('COM', 'Complete'), ('SUS', 'Suspension'), ('CNX', 'Canceled')], default=0, max_length=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('client_name', models.CharField(max_length=256, null=True)),
                ('client_email', models.EmailField(max_length=256, null=True)),
                ('client_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('repo', models.URLField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
