# Generated by Django 3.1.3 on 2020-11-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201120_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
