# Generated by Django 3.1.3 on 2020-11-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201120_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTasks',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
    ]
