# Generated by Django 3.1.3 on 2020-11-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201120_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_number',
        ),
    ]
