# Generated by Django 3.1.3 on 2020-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201120_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPN', 'Open'), ('COM', 'Complete'), ('SUS', 'Suspended')], default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPN', 'Open'), ('COM', 'Complete'), ('SUS', 'Suspended')], default=0, max_length=3),
        ),
    ]
